# Site settings
title:       Gavin Gilmour
email:       me@gavin.coffee
author:      Gavin Gilmour
description: "personal blog"
baseurl:     ""
url:         "http://gavin.coffee"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: gaving
stackoverflow_id: 126893
twitter_username: vesech
google_plus_id:
linkedin_username: gilmourgavin
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
